[workspace]
members = [ "pyrxing", "reader_core"]
resolver = "3"

[workspace.package]
version = "0.3.0"
authors = ["Takanobu Nagumo <nagumo5683@gmail.com>"]
license = "MIT"
edition = "2024"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
debug = false
